SHOW VARIABLES LIKE "autocommit";
DROP TABLE test1;
DROP TABLE test2;
DROP TABLE test3;


CREATE TABLE test2(
	a INT PRIMARY KEY,
	b INT
	
);


SET autocommit = 1;

SET autocommit = 0;
START TRANSACTION;
INSERT INTO test.test2 VALUES(2,2);
INSERT INTO test.test2 VALUES(1,2);

COMMIT;


SELECT * FROM test.test2;
ROLLBACK;




SELECT @@transaction_isolation;


SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET autocommit = 0;
START TRANSACTION;
SELECT * FROM test2;
COMMIT;



