DROP PROCEDURE IF EXISTS a;
DELIMITER $
CREATE PROCEDURE a(IN num INT, OUT result VARCHAR(10))
BEGIN
	CASE 
	WHEN num>=90 THEN SELECT  "A" INTO result;
	WHEN num>=80 THEN SELECT  "B" INTO result;
	WHEN num>=60 THEN SELECT  "C" INTO result;
	ELSE SELECT  "D" INTO result;
	END CASE;	
END $
DELIMITER ;
SELECT @result;
CALL a(90,@result);
SELECT @result;